version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Kiev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fast_api:
    environment:
      TZ: Europe/Kiev
    build: .
    command: uvicorn main:create_app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/src
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
